# Generated by Django 3.2.9 on 2021-11-24 19:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
